version: 2
jobs:
  build:
    docker:
      - image: node:10.15.3-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: yarn coverage

      - run:
          name: Report to Codecov
          command: yarn codecov --token=$CODECOV_TOKEN
